name: Release

# The workflow will be run when a commit is tagged with a version number
on:
  push:
    tags:
    - 'v*'

env:
  SOLUTION_NAME: ${{ github.event.repository.name }}

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: plugin

    - name: Clone BakkesmodSDK
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: bakkesmodorg/BakkesModSDK
        path: plugin/bakkesmodsdk

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: msbuild plugin/${{ github.event.repository.name }}.sln -p:BakkesModPath=$env:GITHUB_WORKSPACE/plugin;Environment=GitHub;Configuration=Release

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}\plugin\plugins\${{ github.event.repository.name }}.dll
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}