name: Setup repository
run-name: Plugin template setup in ${{ github.event.repository.name }} by @${{ github.actor }}
permissions:
  actions: write
  contents: write
env:
  REPO_SETUP_TOKEN: ${{ secrets.REPO_SETUP_TOKEN }}
defaults:
  run:
    shell: pwsh
on:
  workflow_dispatch:
  push:
    paths:
      - cookiecutter.json
jobs:
  setup:
    name: Initialize Repo
    if: ${{ github.event.repository.is_template == false }}
    runs-on: windows-latest
    steps:
      - name: Check Secret
        run: |
          if ($null -eq $env:REPO_SETUP_TOKEN) {
            echo "::error title=REPO_SETUP_TOKEN was not set::Please create a new secret with workflow permissions and add it to the repository with the name REPO_SETUP_TOKEN."
          }
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SETUP_TOKEN }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install cookiecutter

      - name: Scaffolding Repository
        # cookiecutter is command-line utility to create projects from templates
        # https://github.com/cookiecutter/cookiecutter
        #
        # --no-input      Do not prompt for parameters and only use
        #                 cookiecutter.json file content
        #
        # --output-dir    Where to output the generated project dir into
        run: 'cookiecutter . --no-input plugin_name=${{ github.event.repository.name }} plugin_description="${{ github.event.repository.description }}" output_dir=".temp"'

      - name: Prepare root directory
        # Remove all files and folder except .git/ and .temp/
        run: |
          Get-ChildItem -Force -Exclude .git, .temp | Remove-Item -Recurse -Force -Verbose

      - name: Move files to root
        # The .temp/ folder contains a single folder which is the
        # generated project by cookiecutter. We want to move all the project
        # files into the root directory so we can reinitialize git in the next step
        run: |
          Move-Item -Path "./.temp/*" -Destination $PWD -Force -Verbose
          Remove-Item -Path ".\.temp" -Force -Verbose

      - name: Reinitialize git repository
        # Reinitialize git after scaffolding this repository.
        # We use `git checkout --orphan` to create a branch in a git init-like state.
        # By force pushing this as `main` we end up with a new clean git history.
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout --orphan temp-branch
          git rm -rf .
          git add .
          git commit -m 'Initial commit'
          git push origin HEAD:${{ github.ref }} -f

      - name: Remove secret REPO_SETUP_TOKEN
        # After re-initializing the repository, we can remove the `REPO_SETUP_TOKEN` secret.
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$GITHUB_REPOSITORY/actions/secrets/REPO_SETUP_TOKEN